workflows:
  android-build:
    name: Sadeem Android APK Build
    environment:
      flutter: stable
      groups:
        - fadaa_keys
    scripts:
      - name: Fix Android Folder
        script: flutter create .
      - name: Add Internet Permission
        script: perl -pi -e 'print "<uses-permission android:name=\"android.permission.INTERNET\"/>\n" if /<application/' android/app/src/main/AndroidManifest.xml
      - name: Create .env file for secrets in assets folder
        script: |
          mkdir -p assets
          echo "SUPABASE_URL=$SUPABASE_URL" > assets/.env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> assets/.env
          echo "GEMINI_KEY_1=$GEMINI_KEY_1" >> assets/.env
          echo "GEMINI_KEY_2=$GEMINI_KEY_2" >> assets/.env
          echo "GEMINI_KEY_3=$GEMINI_KEY_3" >> assets/.env
          echo "GEMINI_KEY_4=$GEMINI_KEY_4" >> assets/.env
      - name: Get Flutter packages
        script: flutter pub get
      # ✨ أمر سديم السحري لتركيب الأيقونة
      - name: Generate Sadeem App Icon
        script: flutter pub run flutter_launcher_icons
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
