workflows:
  android-build:
    name: Fadaa Android APK Build
    environment:
      flutter: stable
      groups:
        - fadaa_keys # تأكد أن هذا نفس اسم المجموعة التي أنشأتها للمفاتيح السرية
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk