workflows:
  android-build:
    name: Fadaa Android APK Build
    environment:
      flutter: stable
      groups:
        - fadaa_keys
    scripts:
      - name: Fix Android Folder
        script: flutter create .
      - name: Create .env file for secrets
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "GEMINI_KEY_1=$GEMINI_KEY_1" >> .env
          echo "GEMINI_KEY_2=$GEMINI_KEY_2" >> .env
          echo "GEMINI_KEY_3=$GEMINI_KEY_3" >> .env
          echo "GEMINI_KEY_4=$GEMINI_KEY_4" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
